# Generated by Django 5.0.3 on 2024-03-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
