# Generated by Django 5.0.3 on 2024-04-11 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_address_customuser_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='practices',
            field=models.ManyToManyField(blank=True, related_name='user_practices', to='main.practice'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_practices', to=settings.AUTH_USER_MODEL),
        ),
    ]
