# Generated by Django 5.0.3 on 2024-04-09 22:38

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from main.models import CustomUser

def create_groups(apps, schema_editor):
    members_group, created = Group.objects.get_or_create(name='Members')
    coaches_group, created = Group.objects.get_or_create(name='Coaches')

    content_type = ContentType.objects.get_for_model(CustomUser)
    members_group.permissions.add(
        Permission.objects.get(content_type=content_type, codename='view_practice'),
        Permission.objects.get(content_type=content_type, codename='view_announcement'),
    )
    coaches_group.permissions.add(
        Permission.objects.get(content_type=content_type, codename='view_practice'),
        Permission.objects.get(content_type=content_type, codename='add_practice'),
        Permission.objects.get(content_type=content_type, codename='change_practice'),
        Permission.objects.get(content_type=content_type, codename='delete_practice'),
        Permission.objects.get(content_type=content_type, codename='view_announcement'),
        Permission.objects.get(content_type=content_type, codename='add_announcement'),
        Permission.objects.get(content_type=content_type, codename='change_announcement'),
        Permission.objects.get(content_type=content_type, codename='delete_announcement'),
    )
class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_coach_user_customuser_and_more'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
