# Generated by Django 5.0.3 on 2024-04-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_customuser_practices'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
