# Generated by Django 5.0.3 on 2024-04-12 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customuser_options_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target',
            field=models.ManyToManyField(blank=True, related_name='targeted_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
