# Generated by Django 5.0.3 on 2024-04-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_announcement_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_practices',
            field=models.ManyToManyField(blank=True, related_name='targeted_practices', to='main.practice'),
        ),
    ]
